# Generated by Django 3.2.12 on 2022-03-06 01:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='brother_code',
        ),
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='mysite/static/img/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='code',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(upload_to='mysite/static/img/'),
        ),
    ]
