# Generated by Django 3.2.12 on 2022-03-06 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220306_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_name',
            field=models.CharField(default='image', max_length=128),
            preserve_default=False,
        ),
    ]
