# Generated by Django 3.2.12 on 2022-03-06 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_cover_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cover_name',
        ),
    ]
